# Generated by Django 5.1.1 on 2024-09-17 17:50

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('friend_list', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=list, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('from_user_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('to_user_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
