# Generated by Django 5.1.3 on 2024-11-15 20:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('second_user_id', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
    ]
