# Generated by Django 5.1.3 on 2024-11-15 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='second_user_id',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='friend',
            name='user_id',
            field=models.UUIDField(),
        ),
    ]
