# Generated by Django 5.1.1 on 2024-09-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='friend_list',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
