# Generated by Django 5.1 on 2024-09-05 14:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagment', 'init_migrations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='User',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
