# Generated by Django 5.1.1 on 2024-09-16 23:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('match_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('player_one_score', models.IntegerField(default=0)),
                ('player_two_score', models.IntegerField(default=0)),
                ('user_name', models.CharField(max_length=50)),
                ('match_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
