# Generated by Django 5.1.1 on 2024-10-02 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='twofa_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='twofa_code_expiry',
            field=models.DateTimeField(null=True),
        ),
    ]
