# Generated by Django 5.1.1 on 2024-10-04 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_user_twofa_code_user_twofa_code_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='twofa_code_expiry',
        ),
    ]
