# Generated by Django 5.1.2 on 2024-10-21 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_remove_user_twofa_code_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='twofa_code_expiry',
            field=models.DateTimeField(null=True),
        ),
    ]
