# Generated by Django 5.1.3 on 2024-11-11 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_user_last_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_activity',
        ),
    ]
