# Generated by Django 5.1.3 on 2024-11-11 19:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0007_remove_user_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_hearbeat',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
