# Generated by Django 5.1.3 on 2024-11-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0008_user_last_hearbeat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatars/icelebi.jpg', upload_to='avatars/'),
        ),
    ]
